// Generated by Wrangler by running `wrangler types`

interface Env {
	WORKER_ENV: string;
	CARDIO_STORE: DurableObjectNamespace<import("./src/index").CardioStore>;
	PasswordHasher: Fetcher;
}
declare module "*.sql" {
	const value: string;
	export default value;
}